apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: ${CICD_PROJECT_ID}
  labels:
    field.cattle.io/projectId: ${CICD_PROJECT_NAME}
  name: php-example-${CICD_PROJECT_NAME}
---
kind: Service
apiVersion: v1
metadata:
  name: php-example-service
  namespace: php-example-${CICD_PROJECT_NAME}
spec:
  selector:
    app: php-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-example
  namespace: php-example-${CICD_PROJECT_NAME}
  labels:
    app: php-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-example
  template:
    metadata:
      labels:
        app: php-example
    spec:
      containers:
      - name: php
        image: ${CICD_LOCAL_REGISTRY}/php-example:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
